import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { raleway } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${raleway.className} antialiased w-screen h-screen`}>
        {children}
      </body>
    </html>
  );
}
